# -*- coding: utf-8 -*-
"""api.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G5-g7GTzVmTVzBNol4FMWmbFQvRGIPLy
"""

!pip install fastapi

from fastapi import FastAPI
import openai

# Initialize FastAPI app
app = FastAPI()

# Set your OpenAI API key
openai.api_key = "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"

@app.get("/generate-image")
async def generate_image(prompt: str):
    """
    Endpoint to generate an image using DALL·E.
    """
    try:
        response = openai.Image.create(
            prompt=prompt,
            n=1,
            size="1024x1024"
        )
        image_url = response['data'][0]['url']
        return {"url": image_url}
    except Exception as e:
        return {"error": str(e)}

!git clone https://github.com/Hamoudy91/dalle-image-api
!cd dalle-image-api