# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qDKz4NNmhZ-_Tcs9Pk9LkChIGPi5-kgY
"""

!pip install fastapi

!pip install openai requests moviepy

import openai

# Replace with your actual API key
openai.api_key = "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"

import openai

def generate_image(prompt):
    """Generates an image using the OpenAI API.

    Args:
        prompt: The text prompt to generate the image from.

    Returns:
        The URL of the generated image.
    """
    response = openai.images.generate(  # Use openai.images.generate instead of openai.Image.create )
        prompt=prompt,
        n=1,
        size="1024x1024"
    )
    image_url = response.data[0].url  # Access the image URL from response.data
    return image_url

# Test the function
prompt = "A futuristic city with flying cars at sunset"
image_url = generate_image(prompt)
print(f"Generated Image URL: {image_url}")

from IPython.display import Image, display

# Display the image
display(Image(url=image_url))

def generate_image_sequence(prompts):
    urls = []
    for prompt in prompts:
        url = generate_image(prompt)
        urls.append(url)
    return urls

prompts = [
    "A futuristic city at sunrise",
    "A futuristic city at noon",
    "A futuristic city at sunset",
    "A futuristic city at night"
]
image_urls = generate_image_sequence(prompts)
print(image_urls)

import requests
from PIL import Image as PILImage
from io import BytesIO

def download_image(url, filename):
    response = requests.get(url)
    img = PILImage.open(BytesIO(response.content))
    img.save(filename)

# Download all images
for i, url in enumerate(image_urls):
    download_image(url, f"image_{i}.png")

from moviepy.editor import ImageSequenceClip

def create_video(image_files, output_file="output_video.mp4", fps=1):
    clip = ImageSequenceClip(image_files, fps=fps)
    clip.write_videofile(output_file)

image_files = [f"image_{i}.png" for i in range(len(image_urls))]
create_video(image_files)

from IPython.display import Video

Video("output_video.mp4", embed=True)

user_prompt = input("Describe the scene you want to generate: ")
image_url = generate_image(user_prompt)
display(Image(url=image_url))